Module5 task2
htmlacademy-ecmascript/166671-cinemaddict-16 pull request #9
Opened 2021-12-19 12:28 UTC by vpalex999

2021-12-19 20:34 UTC, at31oldfox requested changes

2021-12-19 20:34 UTC, at31oldfox commented on package.json
> +    "dayjs": "^1.10.7"
используем точные указания версий

2021-12-19 20:34 UTC, at31oldfox commented on src/presenter/movie-list-presenter.js
> +  #currentSortType = SortType.DEFAULT;
почему # ?

2021-12-20 04:13 UTC, vpalex999 commented on src/presenter/movie-list-presenter.js
> +  #currentSortType = SortType.DEFAULT;
#currentSortType - приватный, используется только внутри класса и не является частью внешнего интерфейса.

Если в будущем значение этого атрибута будет нужно дугим клиентам, то сделаю геттер.

2021-12-20 04:19 UTC, vpalex999 commented on package.json
> +    "dayjs": "^1.10.7"
исправил

2021-12-21 05:24 UTC, merged